# Generated by Django 3.0.4 on 2020-04-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('aId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('aName', models.CharField(max_length=20)),
                ('aDetail', models.TextField()),
                ('aCreatedOn', models.DateTimeField(auto_now_add=True)),
                ('aUpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app',
            },
        ),
    ]
